### ISSUE TITLE
aarch64 运行demo报错，win 11 x64下没问题

### ISSUE THREAD

**Issue by x-light-ai** [k2-fsa/sherpa-onnx#1083]
运行官方 demo ，speech-recognition-from-microphone 

aarch64 运行报错，win 11 x64下运行正常

`dotnet speech-recognition-from-microphone.dll --tokens=sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/tokens.txt --encoder=sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/encoder-epoch-20-avg-1-chunk-16-left-128.int8.onnx --decoder=sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/decoder-epoch-20-avg-1-chunk-16-left-128.onnx --joiner=sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/joiner-epoch-20-avg-1-chunk-16-left-128.int8.onnx
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'sherpa-onnx-c-api' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.5/sherpa-onnx-c-api.so: cannot open shared object file: No such file or directory
/home/sherpa/sherpa-onnx-c-api.so: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.5/libsherpa-onnx-c-api.so: cannot open shared object file: No such file or directory
/home/sherpa/libsherpa-onnx-c-api.so: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.5/sherpa-onnx-c-api: cannot open shared object file: No such file or directory
/home/sherpa/sherpa-onnx-c-api: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.5/libsherpa-onnx-c-api: cannot open shared object file: No such file or directory
/home/sherpa/libsherpa-onnx-c-api: cannot open shared object file: No such file or directory

   at SherpaOnnx.OnlineRecognizer.CreateOnlineRecognizer(OnlineRecognizerConfig& config)
   at SherpaOnnx.OnlineRecognizer..ctor(OnlineRecognizerConfig config)
   at SpeechRecognitionFromMicrophone.Run(Options options) in F:\Study\sherpa-onnx-master\sherpa-onnx-master\dotnet-examples\speech-recognition-from-microphone\Program.cs:line 156
   at SpeechRecognitionFromMicrophone.<>c.<Main>b__1_1(Options options) in F:\Study\sherpa-onnx-master\sherpa-onnx-master\dotnet-examples\speech-recognition-from-microphone\Program.cs:line 89
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at SpeechRecognitionFromMicrophone.Main(String[] args) in F:\Study\sherpa-onnx-master\sherpa-onnx-master\dotnet-examples\speech-recognition-from-microphone\Program.cs:line 88`

**Comment by csukuangfj** [comment]
你说的 aarch64, 是 linux aarch64 么？
然后你用了 .Net ?

**Comment by csukuangfj** [comment]
> > 你说的 aarch64, 是 linux aarch64 么？ 然后你用了 .Net ?
> 
> 是的.net8 + linux arm64 这个组合有什么问题吗？

![Screenshot 2024-07-08 at 16 07 09](https://github.com/k2-fsa/sherpa-onnx/assets/5284924/1a1d85d1-9a0c-450c-946d-dd62d14a0380)


可以使用 v1.10.11, 然后再测试下么？

开始没有增加 linux arm64 的.Net 支持，现在最新版 1.10.11 支持 linux arm64 了.

**Comment by csukuangfj** [comment]
现在可以跑了吗？
