### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libsherpa-onnx-jni.so" not found

### ISSUE THREAD

**Issue by AliMoradiSabzKoohi** [k2-fsa/sherpa-onnx#1279]
Shutting down VM
2024-08-22 18:29:57.439  4632-4632  AndroidRuntime          com.k2fsa.sherpa.onnx                E  FATAL EXCEPTION: main
                                                                                                    Process: com.k2fsa.sherpa.onnx, PID: 4632
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libsherpa-onnx-jni.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at com.k2fsa.sherpa.onnx.OnlineRecognizer.<clinit>(OnlineRecognizer.kt:146)
                                                                                                    	at com.k2fsa.sherpa.onnx.MainActivity.initModel(MainActivity.kt:215)
                                                                                                    	at com.k2fsa.sherpa.onnx.MainActivity.onCreate(MainActivity.kt:72)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8975)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8944)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by csukuangfj** [comment]
Please follow our Android doc.

**Comment by csukuangfj** [comment]
Will close it if no response is received in the following days.
