### ISSUE TITLE
if "sec-websocket-key" not in request_headers:

### ISSUE THREAD

**Issue by Fransie-dev** [k2-fsa/sherpa-onnx#1574]
Hi, just wanted to point out that I had to change streaming_server.py:587

```
        if "sec-websocket-key" not in request_headers:
```
to 
```
        if "sec-websocket-key" not in request_headers.headers.keys():
```
to get it to work / accept incoming requests. Original error message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/websockets/asyncio/server.py", line 353, in conn_handler
    await connection.handshake(
  File "/usr/local/lib/python3.11/dist-packages/websockets/asyncio/server.py", line 204, in handshake
    raise self.protocol.handshake_exc
  File "/usr/local/lib/python3.11/dist-packages/websockets/asyncio/server.py", line 146, in handshake
    response = await response
               ^^^^^^^^^^^^^^
  File "/workspace/sherpa-onnx/./python-api-examples/streaming_server.py", line 588, in process_request
    if "sec-websocket-key" not in request_headers:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'Request' is not iterable
```

**Comment by csukuangfj** [comment]
Could you make a pull request?

**Comment by Fransie-dev** [comment]
I don't think I have the right permissions:

remote: Permission to k2-fsa/sherpa-onnx.git denied

**Comment by csukuangfj** [comment]
Anyone can make.a.pull request.

Not everyone can push directly to.the. current repo.
