### ISSUE TITLE
elecron开发，主进程引入test-offline-tts-zh.js，报错'./vits-icefall-zh-aishell3/phone.fst' does not exist文件找不到

### ISSUE THREAD

**Issue by nickchainnb** [k2-fsa/sherpa-onnx#1600]
elecron开发，引用nodejs-examples 离线tts,test-offline-tts-zh.js, 在主进程中引入，报错'./vits-icefall-zh-aishell3/phone.fst' does not exist文件找不到
![微信图片_20241206154525](https://github.com/user-attachments/assets/7e0c0490-be5a-4d8c-91ef-3f4a01cf4e2e)
![微信图片_20241206154536](https://github.com/user-attachments/assets/a8c07177-c288-45c1-ab86-a38fdf3456ef)

**Comment by csukuangfj** [comment]
如果你不会调试，不会相对路径，建议你使用绝对路径。

**Comment by nickchainnb** [comment]
找到问题了，确实是相对路径问题，用了绝对路径

**Comment by csukuangfj** [comment]
你可以把当前目录打印出来，看是相对哪个目录

**Comment by ExploringTheCodeWorld** [comment]
你好，可以问一下electron中使用[sherpa-onnx-node](https://www.npmjs.com/package/sherpa-onnx-node)为什么报错吗？App threw an error during load
Error: Could not find sherpa-onnx-node. Tried

../build/Release/sherpa-onnx.node
../build/Debug/sherpa-onnx.node
./node_modules/sherpa-onnx-win-x64/sherpa-onnx.node
../sherpa-onnx-win-x64/sherpa-onnx.node
./sherpa-onnx.node

at Object.<anonymous> (E:\test\electron-test\electron-vite-vue3-win7-main\dist-electron\main.js:29504:9)
at Module._compile (node:internal/modules/cjs/loader:1141:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
at Module.load (node:internal/modules/cjs/loader:1011:32)
at Module._load (node:internal/modules/cjs/loader:846:12)
at f._load (node:electron/js2c/asar_bundle:2:13377)
at loadApplicationPackage (E:\test\electron-test\electron-vite-vue3-win7-main\node_modules\electron\dist\resources\default_app.asar\main.js:121:16)
at Object.<anonymous> (E:\test\electron-test\electron-vite-vue3-win7-main\node_modules\electron\dist\resources\default_app.asar\main.js:233:9)
at Module._compile (node:internal/modules/cjs/loader:1141:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)

**Comment by csukuangfj** [comment]
请看https://github.com/l1veIn/lol-wom-electron
别人都把sherpa-onnx用在electron 里面了。建议去学一下
