### ISSUE TITLE
如何在centos7 系统上安装gpu版本（How to install gpu version on centos 7 system）

### ISSUE THREAD

**Issue by fierceX** [k2-fsa/sherpa-onnx#1665]
预编译的版本提示glibc的版本过低，我尝试手动编译安装，但是还会报glbic的问题：
（The precompiled version suggested that the version of glibc was too low. I tried to compile and install it manually, but there was also a problem with glbic）
```
/home/audio/miniconda3/envs/k2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: libz.so.1, needed by ../../_deps/onnxruntime-src/lib/libonnxruntime.so, not found (try using -rpath or -rpath-link)
/home/audio/miniconda3/envs/k2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../../_deps/onnxruntime-src/lib/libonnxruntime.so: undefined reference to `logf@GLIBC_2.27'
/home/audio/miniconda3/envs/k2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../../_deps/onnxruntime-src/lib/libonnxruntime.so: undefined reference to `powf@GLIBC_2.27'
/home/audio/miniconda3/envs/k2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../../_deps/onnxruntime-src/lib/libonnxruntime.so: undefined reference to `expf@GLIBC_2.27'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/sherpa-onnx-offline-audio-tagging] Error 1
make[1]: *** [sherpa-onnx/csrc/CMakeFiles/sherpa-onnx-offline-audio-tagging.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/audio/miniconda3/envs/k2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: libz.so.1, needed by ../../_deps/onnxruntime-src/lib/libonnxruntime.so, not found (try using -rpath or -rpath-link)
/home/audio/miniconda3/envs/k2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../../_deps/onnxruntime-src/lib/libonnxruntime.so: undefined reference to `logf@GLIBC_2.27'
/home/audio/miniconda3/envs/k2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../../_deps/onnxruntime-src/lib/libonnxruntime.so: undefined reference to `powf@GLIBC_2.27'
/home/audio/miniconda3/envs/k2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../../_deps/onnxruntime-src/lib/libonnxruntime.so: undefined reference to `expf@GLIBC_2.27'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/sherpa-onnx-offline] Error 1
make[1]: *** [sherpa-onnx/csrc/CMakeFiles/sherpa-onnx-offline.dir/all] Error 2
/home/audio/miniconda3/envs/k2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: libz.so.1, needed by ../../_deps/onnxruntime-src/lib/libonnxruntime.so, not found (try using -rpath or -rpath-link)
/home/audio/miniconda3/envs/k2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../../_deps/onnxruntime-src/lib/libonnxruntime.so: undefined reference to `logf@GLIBC_2.27'
/home/audio/miniconda3/envs/k2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../../_deps/onnxruntime-src/lib/libonnxruntime.so: undefined reference to `powf@GLIBC_2.27'
/home/audio/miniconda3/envs/k2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../../_deps/onnxruntime-src/lib/libonnxruntime.so: undefined reference to `expf@GLIBC_2.27'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/sherpa-onnx-keyword-spotter] Error 1
make[1]: *** [sherpa-onnx/csrc/CMakeFiles/sherpa-onnx-keyword-spotter.dir/all] Error 2
/home/audio/miniconda3/envs/k2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: libz.so.1, needed by ../../_deps/onnxruntime-src/lib/libonnxruntime.so, not found (try using -rpath or -rpath-link)
/home/audio/miniconda3/envs/k2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../../_deps/onnxruntime-src/lib/libonnxruntime.so: undefined reference to `logf@GLIBC_2.27'
/home/audio/miniconda3/envs/k2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../../_deps/onnxruntime-src/lib/libonnxruntime.so: undefined reference to `powf@GLIBC_2.27'
/home/audio/miniconda3/envs/k2/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../../_deps/onnxruntime-src/lib/libonnxruntime.so: undefined reference to `expf@GLIBC_2.27'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/sherpa-onnx] Error 1
make[1]: *** [sherpa-onnx/csrc/CMakeFiles/sherpa-onnx.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/audio/sherpa-onnx-1.10.37/setup.py", line 62, in <module>
    setuptools.setup(
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
    return run_commands(dist)
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
    dist.run_commands()
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/dist.py", line 995, in run_command
    super().run_command(command)
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/command/install.py", line 109, in run
    self.do_egg_install()
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/command/install.py", line 167, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/dist.py", line 995, in run_command
    super().run_command(command)
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 177, in run
    cmd = self.call_command('install_lib', warn_dir=False)
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 163, in call_command
    self.run_command(cmdname)
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/dist.py", line 995, in run_command
    super().run_command(command)
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 19, in run
    self.build()
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/_distutils/command/install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/dist.py", line 995, in run_command
    super().run_command(command)
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 99, in run
    _build_ext.run(self)
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
    self._build_extensions_serial()
  File "/home/audio/miniconda3/envs/k2/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/audio/sherpa-onnx-1.10.37/cmake/cmake_extension.py", line 196, in build_extension
    raise Exception(
Exception: 
Build sherpa-onnx failed. Please check the error message.
You can ask for help by creating an issue on GitHub.

Click:
        https://github.com/k2-fsa/sherpa-onnx/issues/new
```
gcc和g++我是通过conda安装的，版本为11，cmake版本是从官网下载的最新版  
（I installed gcc and g++ through conda, version 11, and cmake version is the latest version downloaded from the official website）
```
(k2) [audio@localhost sherpa-onnx-1.10.37]$ gcc --version
gcc (conda-forge gcc 11.4.0-13) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(k2) [audio@localhost sherpa-onnx-1.10.37]$ g++ --version
g++ (conda-forge gcc 11.4.0-13) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(k2) [audio@localhost sherpa-onnx-1.10.37]$ cmake --version
cmake version 3.31.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by csukuangfj** [comment]
请参考

https://github.com/k2-fsa/sherpa-onnx/pull/1586
