### ISSUE TITLE
Runtime issue in Docker Container. ( protobuf parsing failed.)

### ISSUE THREAD

**Issue by Md-Aashiqq** [k2-fsa/sherpa-onnx#224]
---Error logs-------

2023-07-26 10:53:08,085 INFO [streaming_server.py:622] {'encoder_model': './sherpa-onnx-streaming-zipformer-en-2023-06-21/encoder-epoch-99-avg-1.int8.onnx', 'decoder_model': './sherpa-onnx-streaming-zipformer-en-2023-06-21/decoder-epoch-99-avg-1.int8.onnx', 'joiner_model': './sherpa-onnx-streaming-zipformer-en-2023-06-21/joiner-epoch-99-avg-1.int8.onnx', 'tokens': './sherpa-onnx-streaming-zipformer-en-2023-06-21/tokens.txt', 'sample_rate': 16000, 'feat_dim': 80, 'decoding_method': 'greedy_search', 'num_active_paths': 4, 'use_endpoint': 1, 'rule1_min_trailing_silence': 2.4, 'rule2_min_trailing_silence': 1.2, 'rule3_min_utterance_length': 20, 'port': 6006, 'nn_pool_size': 1, 'max_batch_size': 50, 'max_wait_ms': 10, 'max_message_size': 1048576, 'max_queue_size': 32, 'max_active_connections': 500, 'num_threads': 1, 'certificate': None, 'doc_root': './web'}
Traceback (most recent call last):
  File "./streaming_server.py", line 663, in <module>
    main()
  File "./streaming_server.py", line 626, in main
    recognizer = create_recognizer(args)
  File "./streaming_server.py", line 293, in create_recognizer
    recognizer = sherpa_onnx.OnlineRecognizer(
  File "/usr/local/lib/python3.8/dist-packages/sherpa_onnx/online_recognizer.py", line 136, in __init__
    self.recognizer = _Recognizer(recognizer_config)
RuntimeError: Failed to load model because protobuf parsing failed.

--------- Dockerfile.---------
# Use an official Python runtime as a parent image
FROM python:3.7

WORKDIR /app

COPY ./sherpa-onnx-streaming-zipformer-en-2023-06-21 /app/sherpa-onnx-streaming-zipformer-en-2023-06-21

# Copy the rest of the application into the Docker Container
COPY . /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 6006 

# Run streaming_server.py when the container launches
CMD ["python3", "./streaming_server.py", "--encoder=./sherpa-onnx-streaming-zipformer-en-2023-06-21/encoder-epoch-99-avg-1.int8.onnx", "--decoder=./sherpa-onnx-streaming-zipformer-en-2023-06-21/decoder-epoch-99-avg-1.int8.onnx", "--joiner=./sherpa-onnx-streaming-zipformer-en-2023-06-21/joiner-epoch-99-avg-1.int8.onnx","--tokens=./sherpa-onnx-streaming-zipformer-en-2023-06-21/tokens.txt"]

-----------Requirements.txt------------
# Core libraries
numpy>=1.20
# Web Server
websockets==9.1
sherpa-onnx==1.5.4

**Comment by csukuangfj** [comment]
Please follow the doc to download the model.

You can check the model file size and you'll find it doesn't match the one listed in the doc.

**Comment by csukuangfj** [comment]
@Md-Aashiqq 

Have you fixed it?

**Comment by Md-Aashiqq** [comment]
@csukuangfj . yes, its resolved. Thanks
