### ISSUE TITLE
get no attribute 'from_transducer' when trying to run dockerfile

### ISSUE THREAD

**Issue by Caet-pip** [k2-fsa/sherpa-onnx#273]
I am trying to deploy a docker file with sherpa-onnx for making a container that can be run in the cloud but when I am running the container i get this error

docker run -p 6006:6006 transcribe-bancked
2023-08-14 23:41:57,398 INFO [streaming_server.py:719] {'encoder': './sherpa-onnx-streaming-zipformer-en-2023-06-21/encoder-epoch-99-avg-1.int8.onnx', 'decoder': './sherpa-onnx-streaming-zipformer-en-2023-06-21/decoder-epoch-99-avg-1.int8.onnx', 'joiner': './sherpa-onnx-streaming-zipformer-en-2023-06-21/joiner-epoch-99-avg-1.int8.onnx', 'paraformer_encoder': None, 'paraformer_decoder': None, 'tokens': './sherpa-onnx-streaming-zipformer-en-2023-06-21/tokens.txt', 'sample_rate': 16000, 'feat_dim': 80, 'provider': 'cpu', 'decoding_method': 'greedy_search', 'num_active_paths': 4, 'use_endpoint': 1, 'rule1_min_trailing_silence': 2.4, 'rule2_min_trailing_silence': 1.2, 'rule3_min_utterance_length': 20, 'port': 6006, 'nn_pool_size': 1, 'max_batch_size': 50, 'max_wait_ms': 10, 'max_message_size': 1048576, 'max_queue_size': 32, 'max_active_connections': 500, 'num_threads': 2, 'certificate': None, 'doc_root': './python-api-examples/web'}
Traceback (most recent call last):
  File "/app/./streaming_server.py", line 757, in <module>
    main()
  File "/app/./streaming_server.py", line 722, in main
    recognizer = create_recognizer(args)
  File "/app/./streaming_server.py", line 336, in create_recognizer
    recognizer = sherpa_onnx.OnlineRecognizer.from_transducer(
AttributeError: type object 'OnlineRecognizer' has no attribute 'from_transducer'

This is my docker file code:
# Use an official Python runtime as a parent image
FROM python:3.10

WORKDIR /app

COPY ./sherpa-onnx-streaming-zipformer-en-2023-06-21 /app/sherpa-onnx-streaming-zipformer-en-2023-06-21

# Copy the rest of the application into the Docker Container

COPY . /app/

# Install any needed packages specified in requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container

EXPOSE 6006

# Run streaming_server.py when the container launches
CMD ["python3", "./streaming_server.py", "--encoder=./sherpa-onnx-streaming-zipformer-en-2023-06-21/encoder-epoch-99-avg-1.int8.onnx", "--decoder=./sherpa-onnx-streaming-zipformer-en-2023-06-21/decoder-epoch-99-avg-1.int8.onnx", "--joiner=./sherpa-onnx-streaming-zipformer-en-2023-06-21/joiner-epoch-99-avg-1.int8.onnx","--tokens=./sherpa-onnx-streaming-zipformer-en-2023-06-21/tokens.txt"]

This is requirements.txt code:
# Core libraries
numpy>=1.20
websockets
sherpa-onnx==1.5.4

I have the streaming_server.py and http_server.py file along with model file in the directory, what is causing the error?

**Comment by csukuangfj** [comment]
The latest sherpa_onnx version is 1.7.6. However, you are using `sherpa-onnx==1.5.4`.

Please update your sherpa-onnx.
