### ISSUE TITLE
Cannot find file    ..\node_modules\sherpa-onnx\lib\win-x64\sherpa-onnx-c-api.dll

### ISSUE THREAD

**Issue by deuemcak** [k2-fsa/sherpa-onnx#449]
win10, 
Node.js v18.14.2 , 
sherpa-onnx@1.8.12
test-online-paraformer.js 

G:\nodejs\node_modules\sherpa-onnx\index.js:262
throw new Error(`Cannot find file ${soname}. Please make sure you have run
^

Error: Cannot find file G:\nodejs\node_modules\sherpa-onnx\lib\win-x64\sherpa-onnx-c-api.dll. Please make sure you have run
./build.sh
at Object.<anonymous> (G:\nodejs\node_modules\sherpa-onnx\index.js:262:9)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (G:\nodejs\test_mp3_text.js:15:21)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

------------------------

然后去 G:\nodejs\node_modules\sherpa-onnx\lib\ 路径下看，只有【windows-x64】没有【win-x64】
引入的时候，vscode有提示：无法找到模块“sherpa-onnx”的声明文件。“g:/nodejs/node_modules/sherpa-onnx/index.js”隐式拥有 "any" 类型。

![微信截图_20231125174924](https://github.com/k2-fsa/sherpa-onnx/assets/14887476/8de6cabe-6560-4d04-b3cb-1477ad700e80)
![微信截图_20231125173056](https://github.com/k2-fsa/sherpa-onnx/assets/14887476/812b6f09-419f-4e12-b66e-08d83e52e7a3)
![微信截图_20231125172837](https://github.com/k2-fsa/sherpa-onnx/assets/14887476/906fb770-9714-4682-8707-8d1b47457325)

--------------------
把【windows-x64】改成【win-x64】，报错：
G:\nodejs\node_modules\ffi-napi\lib\dynamic_library.js:67
if (match = err.match(/^(([^ \t()])+\.so([^ \t:()])*):([ \t])*/)) {
^

TypeError: Cannot read properties of null (reading 'match')
at new DynamicLibrary (G:\nodejs\node_modules\ffi-napi\lib\dynamic_library.js:67:21)
at Object.Library (G:\nodejs\node_modules\ffi-napi\lib\library.js:47:10)
at Object.<anonymous> (G:\nodejs\node_modules\sherpa-onnx\index.js:268:28)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (G:\nodejs\test_mp3_text.js:15:21)

**Comment by csukuangfj** [comment]
could you use node 13？

**Comment by deuemcak** [comment]
> could you use node 13？

Node.js 13.14.0  ?

**Comment by deuemcak** [comment]
> could you use node 13？

ok，降低版本到 Node.js 13.14.0，可以了。谢谢.

**Comment by csukuangfj** [comment]
> > could you use node 13？
> 
> ok，降低版本到 Node.js 13.14.0，可以了。谢谢.

https://github.com/k2-fsa/sherpa-onnx/blob/66cad9fa93adb323eac51b018f8cad0423869ef5/scripts/nodejs/index.js#L10-L14

**Comment by csukuangfj** [comment]
> 然后去 G:\nodejs\node_modules\sherpa-onnx\lib\ 路径下看，只有【windows-x64】没有【win-x64】


谢谢指出。已在最新版中修正

![Screenshot 2023-11-25 at 18 20 03](https://github.com/k2-fsa/sherpa-onnx/assets/5284924/370d3f82-f2c8-4532-b66e-703627c3a3cf)

**Comment by deuemcak** [comment]
> > > could you use node 13？
> > 
> > 
> > ok，降低版本到 Node.js 13.14.0，可以了。谢谢.
> 
> https://github.com/k2-fsa/sherpa-onnx/blob/66cad9fa93adb323eac51b018f8cad0423869ef5/scripts/nodejs/index.js#L10-L14

谢谢，以后会注意看这块内容。

**Comment by csukuangfj** [comment]
> > > > could you use node 13？
> > > 
> > > 
> > > ok，降低版本到 Node.js 13.14.0，可以了。谢谢.
> > 
> > 
> > https://github.com/k2-fsa/sherpa-onnx/blob/66cad9fa93adb323eac51b018f8cad0423869ef5/scripts/nodejs/index.js#L10-L14
> 
> 谢谢，以后会注意看这块内容。

我们还没有完善。以后会在文档中注明。

你是可以在 windows 上成功运行了么？

**Comment by deuemcak** [comment]
> > > > > could you use node 13？
> > > > 
> > > > 
> > > > ok，降低版本到 Node.js 13.14.0，可以了。谢谢.
> > > 
> > > 
> > > https://github.com/k2-fsa/sherpa-onnx/blob/66cad9fa93adb323eac51b018f8cad0423869ef5/scripts/nodejs/index.js#L10-L14
> > 
> > 
> > 谢谢，以后会注意看这块内容。
> 
> 我们还没有完善。以后会在文档中注明。
> 
> 你是可以在 windows 上成功运行了么？

在win10 下运行成功了，可以正确识别示例里的音频文件。

**Comment by csukuangfj** [comment]
> 在win10 下运行成功了，可以正确识别示例里的音频文件。

太棒啦！

**Comment by obenxiaohai** [comment]
![Uploading 临时打印日志.png…]()
我现在用的nodejs 13.14.0版本，原本的vs2022也换成了新装的vs2017，x64的。然而还是报这个错误，求解。

**Comment by csukuangfj** [comment]
@deuemcak  能帮忙看下么？

**Comment by csukuangfj** [comment]
@obenxiaohai 

请用最新的 npm 包, 即 sherpa-onnx >= 1.9.11

你不需要再安装 visual studio 了。

我们目前采用的是 WebAssembly Module.  NodeJS 直接调用编译好的 wasm 模块，这个是跨平台的。不需要通过 FFI 去掉用 动态链接库了.
