### ISSUE TITLE
No implementation found for long com.k2fsa.sherpa.onnx.OfflineTts.newFromFile

### ISSUE THREAD

**Issue by muhammedjailam** [k2-fsa/sherpa-onnx#499]
When running the SherpaOnnxTts I m getting this error. 

java.lang.UnsatisfiedLinkError: No implementation found for long com.k2fsa.sherpa.onnx.OfflineTts.newFromFile(com.k2fsa.sherpa.onnx.OfflineTtsConfig) (tried Java_com_k2fsa_sherpa_onnx_OfflineTts_newFromFile and Java_com_k2fsa_sherpa_onnx_OfflineTts_newFromFile__Lcom_k2fsa_sherpa_onnx_OfflineTtsConfig_2)
             at com.k2fsa.sherpa.onnx.OfflineTts.newFromFile(Native Method)
             at com.k2fsa.sherpa.onnx.OfflineTts.<init>(Tts.kt:53)
             at com.k2fsa.sherpa.onnx.MainActivity.initTts(MainActivity.kt:202)
            at com.k2fsa.sherpa.onnx.MainActivity.onCreate(MainActivity.kt:35)
            
            
The function lacks implantation in the Tts.tk file 

    private external fun newFromFile(
        config: OfflineTtsConfig,
    ): Long
    
How can this be fixed.

**Comment by csukuangfj** [comment]
Could you describe what changes you have made?

**Comment by muhammedjailam** [comment]
I have just copied the SherpaOnnxTts project and follows the instructions from https://k2-fsa.github.io/sherpa/onnx/android/build-sherpa-onnx.html.

I used the prebuilt shared libraries and downloaded - https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-amy-low.tar.bz2 this model. 

Then enabled these three lines
         modelDir = "vits-piper-en_US-amy-low"
         modelName = "en_US-amy-low.onnx"
         dataDir = "vits-piper-en_US-amy-low/espeak-ng-data"
         
Afterwards tried to run the app on device and on emulator. The app compiles and immediately after launch - crashes with the above error in the device log. (viewable in the logcat in Android studio).

**Comment by csukuangfj** [comment]
could you post the url for the prebuilt libraries?

**Comment by csukuangfj** [comment]
Also, please show the jniLibs in your Android Studio.

**Comment by muhammedjailam** [comment]
I m using the prebuilt from this URL https://github.com/k2-fsa/sherpa-onnx/releases/download/v1.9.5/sherpa-onnx-v1.9.6-android.tar.bz2

<img width="169" alt="image" src="https://github.com/k2-fsa/sherpa-onnx/assets/9347984/71f60f3a-c2ae-407a-b161-02d93adfc97d">

**Comment by csukuangfj** [comment]
Thanks for sharing the information. 

Please also post the version of the Android Studio you are using.

Some users were using an outdated Android Studio and had issues with building the APK.

**Comment by muhammedjailam** [comment]
<img width="309" alt="image" src="https://github.com/k2-fsa/sherpa-onnx/assets/9347984/1c04dab3-3d58-4222-9cc2-86f1dde830c2">

Android Studio Hedgehog | 2023.1.1
Build #AI-231.9392.1.2311.11076708, built on November 9, 2023
Runtime version: 17.0.7+0-b2043.56-10550314 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 20
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

**Comment by muhammedjailam** [comment]
I m using the latest version of Android Studio. Any reason for the issue?

**Comment by csukuangfj** [comment]
Sorry that I cannot reproduce your issue using the latest Android Studio.
<img width="524" alt="Screenshot 2023-12-31 at 23 05 22" src="https://github.com/k2-fsa/sherpa-onnx/assets/5284924/11d0964b-3782-4605-a96d-4027cda1c3d6">

**Comment by muhammedjailam** [comment]
Issue resolved.

**Comment by Kymonlucky** [comment]
> Issue resolved.

Hello, how were you able to resolve the issue? Currently facing the same error.

**Comment by csukuangfj** [comment]
> > Issue resolved.
> 
> Hello, how were you able to resolve the issue? Currently facing the same error.

Please show your complete error logs @Kymonlucky

**Comment by Kymonlucky** [comment]
> > > Issue resolved.
> > 
> > 
> > Hello, how were you able to resolve the issue? Currently facing the same error.
> 
> Please show your complete error logs @Kymonlucky

Error Log: 

```
FATAL EXCEPTION: main
Process: com.example.sherpa_test, PID: 5163
java.lang.UnsatisfiedLinkError: No implementation found for long com.example.sherpa_test.OfflineTts.newFromFile(com.example.sherpa_test.OfflineTtsConfig) (tried Java_com_example_sherpa_1test_OfflineTts_newFromFile and Java_com_example_sherpa_1test_OfflineTts_newFromFile__Lcom_example_sherpa_1test_OfflineTtsConfig_2) - is the library loaded, e.g. System.loadLibrary?
	at com.example.sherpa_test.OfflineTts.newFromFile(Native Method)
	at com.example.sherpa_test.OfflineTts.<init>(Tts.kt:54)
	at com.example.sherpa_test.OfflineTts.<init>(Tts.kt:44)
	at com.example.sherpa_test.MainActivityKt.MainScreen(MainActivity.kt:52)
	at com.example.sherpa_test.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:28)
	at com.example.sherpa_test.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:27)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.material3.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:303)
	at androidx.compose.material3.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:285)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:991)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:477)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:90)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3302)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3235)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:725)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1071)
	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3599)
	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:619)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcomposeInto(SubcomposeLayout.kt:500)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:472)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:463)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:447)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:872)
	at androidx.compose.material3.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1.invoke-0kLqBqw(Scaffold.kt:285)
	at androidx.compose.material3.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1.invoke(Scaffold.kt:179)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:709)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:252)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:251)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:500)

``` 


AndroidStudioProjects\sherpa_test\app\src\main\jniLibs:
![image](https://github.com/user-attachments/assets/4ea0af44-b303-4cdf-8541-7b7285b2c427)

**Comment by csukuangfj** [comment]
Please don't change the package name of our code.

You need to keep
https://github.com/k2-fsa/sherpa-onnx/blob/a00d3b482123e65e3544e40ec0360e3d66d47faa/sherpa-onnx/kotlin-api/Tts.kt#L2
unchanged.

**Comment by Kymonlucky** [comment]
> Please don't change the package name of our code.
> 
> You need to keep
> 
> https://github.com/k2-fsa/sherpa-onnx/blob/a00d3b482123e65e3544e40ec0360e3d66d47faa/sherpa-onnx/kotlin-api/Tts.kt#L2
> 
> 
> untouched.

I think that fixed the issue but I am encountering a new one. The app just keeps on crashing. 

Logcat: 
```
---------------------------- PROCESS STARTED (6055) for package com.example.sherpa_test ----------------------------
2025-01-02 18:27:16.353  6055-6055  ziparchive              com.example.sherpa_test              W  Unable to open '/data/data/com.example.sherpa_test/code_cache/.overlay/base.apk/classes4.dm': No such file or directory
2025-01-02 18:27:16.355  6055-6055  ziparchive              com.example.sherpa_test              W  Unable to open '/data/data/com.example.sherpa_test/code_cache/.overlay/base.apk/classes5.dm': No such file or directory
2025-01-02 18:27:16.378  6055-6055  ziparchive              com.example.sherpa_test              W  Unable to open '/data/data/com.example.sherpa_test/code_cache/.overlay/base.apk/classes.dm': No such file or directory
2025-01-02 18:27:16.461  6055-6055  ziparchive              com.example.sherpa_test              W  Unable to open '/data/data/com.example.sherpa_test/code_cache/.overlay/base.apk/classes6.dm': No such file or directory
2025-01-02 18:27:16.462  6055-6055  ziparchive              com.example.sherpa_test              W  Unable to open '/data/app/~~3ThDGNdbSiUAubZ5gFTE6w==/com.example.sherpa_test-OjeRCG5SoV7PZnf78yxGoA==/base.dm': No such file or directory
2025-01-02 18:27:16.462  6055-6055  ziparchive              com.example.sherpa_test              W  Unable to open '/data/app/~~3ThDGNdbSiUAubZ5gFTE6w==/com.example.sherpa_test-OjeRCG5SoV7PZnf78yxGoA==/base.dm': No such file or directory
2025-01-02 18:27:16.563  6055-6055  nativeloader            com.example.sherpa_test              D  Configuring clns-7 for other apk /data/app/~~3ThDGNdbSiUAubZ5gFTE6w==/com.example.sherpa_test-OjeRCG5SoV7PZnf78yxGoA==/base.apk. target_sdk_version=35, uses_libraries=, library_path=/data/app/~~3ThDGNdbSiUAubZ5gFTE6w==/com.example.sherpa_test-OjeRCG5SoV7PZnf78yxGoA==/lib/x86_64:/data/app/~~3ThDGNdbSiUAubZ5gFTE6w==/com.example.sherpa_test-OjeRCG5SoV7PZnf78yxGoA==/base.apk!/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/com.example.sherpa_test
2025-01-02 18:27:16.569  6055-6055  CompatChangeReporter    com.example.sherpa_test              D  Compat change id reported: 202956589; UID 10204; state: ENABLED
2025-01-02 18:27:16.614  6055-6055  GraphicsEnvironment     com.example.sherpa_test              V  Currently set values for:
2025-01-02 18:27:16.614  6055-6055  GraphicsEnvironment     com.example.sherpa_test              V    angle_gl_driver_selection_pkgs=[]
2025-01-02 18:27:16.615  6055-6055  GraphicsEnvironment     com.example.sherpa_test              V    angle_gl_driver_selection_values=[]
2025-01-02 18:27:16.615  6055-6055  GraphicsEnvironment     com.example.sherpa_test              V  Global.Settings values are invalid: number of packages: 0, number of values: 0
2025-01-02 18:27:16.616  6055-6055  GraphicsEnvironment     com.example.sherpa_test              V  Neither updatable production driver nor prerelease driver is supported.
2025-01-02 18:27:16.694  6055-6055  CompatChangeReporter    com.example.sherpa_test              D  Compat change id reported: 279646685; UID 10204; state: ENABLED
2025-01-02 18:27:16.787  6055-6055  CompatChangeReporter    com.example.sherpa_test              D  Compat change id reported: 309578419; UID 10204; state: ENABLED
2025-01-02 18:27:16.922  6055-6055  HWUI                    com.example.sherpa_test              W  Unknown dataspace 0
2025-01-02 18:27:17.291  6055-6059  ple.sherpa_test         com.example.sherpa_test              I  Compiler allocated 5174KB to compile void android.view.ViewRootImpl.performTraversals()
2025-01-02 18:27:17.693  6055-6055  nativeloader            com.example.sherpa_test              D  Load /data/app/~~3ThDGNdbSiUAubZ5gFTE6w==/com.example.sherpa_test-OjeRCG5SoV7PZnf78yxGoA==/base.apk!/lib/x86_64/libsherpa-onnx-jni.so using ns clns-7 from class loader (caller=/data/data/com.example.sherpa_test/code_cache/.overlay/base.apk/classes4.dex): ok
2025-01-02 18:27:17.695  6055-6055  sherpa-onnx             com.example.sherpa_test              W  config:
                                                                                                    OfflineTtsConfig(model=OfflineTtsModelConfig(vits=OfflineTtsVitsModelConfig(model="vits-piper-en_US-amy-low/en_US-amy-low.onnx", lexicon="vits-piper-en_US-amy-low/", tokens="vits-piper-en_US-amy-low/tokens.txt", data_dir="vits-piper-en_US-amy-low/espeak-ng-data", dict_dir="", noise_scale=0.667, noise_scale_w=0.8, length_scale=1), num_threads=2, debug=True, provider="cpu"), rule_fsts="", rule_fars="", max_num_sentences=1)
2025-01-02 18:27:19.254  6055-6055  sherpa-onnx             com.example.sherpa_test              W  ---vits model---
                                                                                                    sample_rate=16000
                                                                                                    has_espeak=1
                                                                                                    comment=piper
                                                                                                    n_speakers=1
                                                                                                    voice=en-us
                                                                                                    language=English
                                                                                                    model_type=vits
                                                                                                    ----------input names----------
                                                                                                    0 input
                                                                                                    1 input_lengths
                                                                                                    2 scales
                                                                                                    ----------output names----------
                                                                                                    0 output
                                                                                                    
---------------------------- PROCESS ENDED (6055) for package com.example.sherpa_test ----------------------------

``` 

MaintActivity.kt
```kotlin
package com.example.sherpa_test

import android.app.Application
import android.content.res.AssetManager
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import com.example.sherpa_test.ui.theme.Sherpa_testTheme
import com.k2fsa.sherpa.onnx.OfflineTts
import com.k2fsa.sherpa.onnx.OfflineTtsConfig
import com.k2fsa.sherpa.onnx.OfflineTtsModelConfig
import com.k2fsa.sherpa.onnx.OfflineTtsVitsModelConfig
import com.k2fsa.sherpa.onnx.getOfflineTtsConfig

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContent {
            Sherpa_testTheme {
                Scaffold(modifier = Modifier.fillMaxSize()) { innerPadding ->
                    var assets = application.assets
                    MainScreen(
                        app_asset = assets,
                        modifier = Modifier
                        .fillMaxSize()
                        .padding(innerPadding)
                    )
                }
            }
        }
    }
}

@Composable
fun MainScreen(app_asset: AssetManager,modifier: Modifier = Modifier) {

    var modelDir: String?
    var modelName: String?
    var ruleFsts: String?
    var ruleFars: String?
    var lexicon: String?
    var dataDir: String?
    var dictDir: String?
    var assets: AssetManager? = app_asset

    modelDir = null
    modelName = null
    ruleFsts = null
    ruleFars = null
    lexicon = null
    dataDir = null
    dictDir = null

    modelDir = "vits-piper-en_US-amy-low"
    modelName = "en_US-amy-low.onnx"
    dataDir = "vits-piper-en_US-amy-low/espeak-ng-data"

    val config = getOfflineTtsConfig(
        modelDir = modelDir!!,
        modelName = modelName!!,
        lexicon = lexicon ?: "",
        dataDir = dataDir ?: "",
        dictDir = dictDir ?: "",
        ruleFsts = ruleFsts ?: "",
        ruleFars = ruleFars ?: "",
    )!!

    val tts = OfflineTts(assetManager = assets, config = config)
    val audio = tts.generateWithCallback(text="“Today as always, men fall into two groups: slaves and free men. Whoever does not have two-thirds of his day for himself, is a slave, whatever he may be: a statesman, a businessman, an official, or a scholar.”", callback=::callback)
    audio.save(filename="test-en.wav")
    tts.release()
    println("Saved to test-en.wav")

    Column(
        modifier = modifier,
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Text(text = "Hello, World")
        Button(onClick = { /*TODO*/ }) {
            Text(text = "Play")
        }
    }
}

fun callback(samples: FloatArray): Int {
    println("callback got called with ${samples.size} samples");

    // 1 means to continue
    // 0 means to stop
    return 1
}
```

**Comment by csukuangfj** [comment]
Please post complete logs.

By the way, before writing your own code, please first try our code.

If you encounter any errors with your own code, please compare by yourself what the correct code from us looks like.

**Comment by Kymonlucky** [comment]
I was already able to resolve the issue. Thanks! @csukuangfj
