### ISSUE TITLE
Macos 14.2.1 Seeking Support

### ISSUE THREAD

**Issue by zijun-he** [k2-fsa/sherpa-onnx#543]
git clone https://github.com/k2-fsa/sherpa-onnx
cd sherpa-onnx
python3 setup.py install
Cloning into 'sherpa-onnx'...
remote: Enumerating objects: 5941, done.
remote: Counting objects: 100% (1325/1325), done.
remote: Compressing objects: 100% (382/382), done.
remote: Total 5941 (delta 991), reused 1089 (delta 892), pack-reused 4616
Receiving objects: 100% (5941/5941), 2.80 MiB | 122.00 KiB/s, done.
Resolving deltas: 100% (3778/3778), done.
running install
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating sherpa_onnx.egg-info
writing sherpa_onnx.egg-info/PKG-INFO
writing dependency_links to sherpa_onnx.egg-info/dependency_links.txt
writing entry points to sherpa_onnx.egg-info/entry_points.txt
writing requirements to sherpa_onnx.egg-info/requires.txt
writing top-level names to sherpa_onnx.egg-info/top_level.txt
writing manifest file 'sherpa_onnx.egg-info/SOURCES.txt'
reading manifest file 'sherpa_onnx.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'sherpa_onnx.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-universal2/egg
running install_lib
running build_py
creating build/lib.macosx-10.9-universal2-cpython-310
creating build/lib.macosx-10.9-universal2-cpython-310/sherpa_onnx
copying sherpa-onnx/python/sherpa_onnx/online_recognizer.py -> build/lib.macosx-10.9-universal2-cpython-310/sherpa_onnx
copying sherpa-onnx/python/sherpa_onnx/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/sherpa_onnx
copying sherpa-onnx/python/sherpa_onnx/cli.py -> build/lib.macosx-10.9-universal2-cpython-310/sherpa_onnx
copying sherpa-onnx/python/sherpa_onnx/utils.py -> build/lib.macosx-10.9-universal2-cpython-310/sherpa_onnx
copying sherpa-onnx/python/sherpa_onnx/offline_recognizer.py -> build/lib.macosx-10.9-universal2-cpython-310/sherpa_onnx
running build_ext
Setting PYTHON_EXECUTABLE to /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
for fast compilation, run:
export SHERPA_ONNX_MAKE_ARGS="-j"; python setup.py install
Setting make_args to "-j4"
build command is:

                cd build/temp.macosx-10.9-universal2-cpython-310

                cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -DCMAKE_INSTALL_PREFIX=/Users/zrz/sherpa-onnx/build/lib.macosx-10.9-universal2-cpython-310/sherpa_onnx  -DBUILD_SHARED_LIBS=ON  -DBUILD_PIPER_PHONMIZE_EXE=OFF  -DBUILD_PIPER_PHONMIZE_TESTS=OFF  -DBUILD_ESPEAK_NG_EXE=OFF  -DBUILD_ESPEAK_NG_TESTS=OFF  -DSHERPA_ONNX_ENABLE_CHECK=OFF  -DSHERPA_ONNX_ENABLE_PYTHON=ON  -DSHERPA_ONNX_ENABLE_PORTAUDIO=ON  -DSHERPA_ONNX_ENABLE_WEBSOCKET=ON  /Users/zrz/sherpa-onnx

                make -j4 install/strip
            
sh: line 3: cmake: command not found
make: *** No rule to make target `install/strip'.  Stop.
Traceback (most recent call last):
  File "/Users/zrz/sherpa-onnx/setup.py", line 91, in <module>
    setuptools.setup(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
    self._build_extensions_serial()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users/zrz/sherpa-onnx/cmake/cmake_extension.py", line 144, in build_extension
    raise Exception(
Exception: 
Build sherpa-onnx failed. Please check the error message.
You can ask for help by creating an issue on GitHub.

**Comment by csukuangfj** [comment]
please first run
```bash
pip install cmake
```

**Comment by csukuangfj** [comment]
@zijun-he 

Have you fixed it?

**Comment by zijun-he** [comment]
Thank you for fixing it
