### ISSUE TITLE
Issue with sampling rate requirement for online_websocket_client_decode_file.py

### ISSUE THREAD

**Issue by tempops** [k2-fsa/sherpa-onnx#613]
When using streaming _server.py to decode files from online_websocket_client_decode_file.py, why is there a requirement of 16000 for sample rate. I get this error if I pass a file with 8000 sample rate:

2024-02-26 12:58:07,703 INFO [online-websocket-client-decode-file.py:159] {'server_addr': 'localhost', 'server_port': 6006, 'samples_per_message': 8000, 'seconds_per_message': 0.1, 'sound_file': '8k.wav'}
Traceback (most recent call last):
  File "/Users/sherpa-onnx/python-api-examples/online-websocket-client-decode-file.py", line 180, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/sherpa-onnx/python-api-examples/online-websocket-client-decode-file.py", line 166, in main
    await run(
  File "/Users/sherpa-onnx/python-api-examples/online-websocket-client-decode-file.py", line 128, in run
    data = read_wave(wave_filename)
  File "/Users/sherpa-onnx/python-api-examples/online-websocket-client-decode-file.py", line 55, in read_wave
    assert f.getframerate() == 16000, f.getframerate()
AssertionError: 8000

I do see that in online_websocket_client_decode_file.py in line 49 it says that sampling rate has to be 16000 but in streaming_server line 177 that you do resampling inside.

Can you provide any clarity on this, thanks!

**Comment by csukuangfj** [comment]
> why is there a requirement of 16000 for sample rate

The model is trained using data of sample rate 16kHz.

The client does not send the data's sample rate to the server, so we have to assume the sample rate is 16000Hz.

There are many sample rates, e.g., 16kHz, 8kHz, 44.1kHz, 22.05kHz, etc. Only one sample rate is correct and here we assume the sample rate is 16kHz.

If the client sends the sample rate to the server along with the samples, then the sample rate on the client side can be arbitrary and the server can resample the samples if the received sample rate is not equal to the expected one.

---

>  but in streaming_server line 177 that you do resampling inside.



> https://github.com/k2-fsa/sherpa-onnx/blob/87a7030c087b4cc7da3d90195f34965d040a7e5d/python-api-examples/streaming_server.py#L177

It means if you send 8kHz data and you change
https://github.com/k2-fsa/sherpa-onnx/blob/87a7030c087b4cc7da3d90195f34965d040a7e5d/python-api-examples/streaming_server.py#L721
to
```
 stream.accept_waveform(sample_rate=8000, waveform=samples) 
```

then we will resample it to 16000Hz inside.

**Comment by tempops** [comment]
Thank you very much, I understood the solution.
