### ISSUE TITLE
run android speaker identification met errors

### ISSUE THREAD

**Issue by tianmala** [k2-fsa/sherpa-onnx#787]
i can gradle successfully this project,
but when i run this app , app will crash
The logcat are:
```
--------- beginning of main
--------- beginning of kernel
--------- beginning of system
2020-01-02 03:13:01.252 32067-32067 Zygote                  com...a.onnx.speaker.identification  W  Unable to open libbeluga.so: dlopen failed: library "libbeluga.so" not found.
2020-01-02 03:13:01.262 32067-32067 .identificatio          com...a.onnx.speaker.identification  I  Late-enabling -Xcheck:jni
2020-01-02 03:13:01.276 32067-32067 .identificatio          com...a.onnx.speaker.identification  I  Unquickening 17 vdex files!
2020-01-02 03:13:01.328 32067-32067 .identificatio          com...a.onnx.speaker.identification  W  DexFile /data/data/com.k2fsa.sherpa.onnx.speaker.identification/code_cache/.studio/instruments-615b09e8.jar is in boot class path but is not in a known location
2020-01-02 03:13:01.345 32067-32067 .identificatio          com...a.onnx.speaker.identification  W  Redefining intrinsic method java.lang.Thread java.lang.Thread.currentThread(). This may cause the unexpected use of the original definition of java.lang.Thread java.lang.Thread.currentThread()in methods that have already been compiled.
2020-01-02 03:13:01.345 32067-32067 .identificatio          com...a.onnx.speaker.identification  W  Redefining intrinsic method boolean java.lang.Thread.interrupted(). This may cause the unexpected use of the original definition of boolean java.lang.Thread.interrupted()in methods that have already been compiled.
2020-01-02 03:13:02.124 32067-32067 NetworkSecurityConfig   com...a.onnx.speaker.identification  D  No Network Security Config specified, using platform default
2020-01-02 03:13:02.125 32067-32067 NetworkSecurityConfig   com...a.onnx.speaker.identification  D  No Network Security Config specified, using platform default
2020-01-02 03:13:02.188 32067-32067 PreviewActivity         com...a.onnx.speaker.identification  D  PreviewActivity has composable com.k2fsa.sherpa.onnx.speaker.identification.MainActivityKt.MainScreenPreview
2020-01-02 03:13:02.201 32067-32067 PreviewActivity         com...a.onnx.speaker.identification  D  Previewing 'MainScreenPreview' without a parameter provider.
2020-01-02 03:13:02.254 32067-32067 WindowManagerImpl       com...a.onnx.speaker.identification  D  add view type=1 pid: 32067 DecorView@7389dcd[]
2020-01-02 03:13:02.254 32067-32067 WindowManagerImpl       com...a.onnx.speaker.identification  D  addView wparams.type= null,use aosp
2020-01-02 03:13:02.255 32067-32067 InputMethodManager      com...a.onnx.speaker.identification  D  createRealInstance displayId = 0
2020-01-02 03:13:02.268 32067-32067 MultiDispl...Controller com...a.onnx.speaker.identification  D  ActivityAnimationController window:com.android.internal.policy.PhoneWindow@3e49c9
2020-01-02 03:13:02.268 32067-32067 MultiDisplayManager     com...a.onnx.speaker.identification  E  getDisplayFromMemoryType invalid memoryType:0
2020-01-02 03:13:02.269 32067-32067 MultiDispl...Controller com...a.onnx.speaker.identification  D  mOriginalMemoryType: 0, mOriginalFlags: -2122252032, mCurrentDisplayId: 0, mScreenW: 2560, mScreenH: 1440
2020-01-02 03:13:02.269 32067-32067 MultiDisplayManager     com...a.onnx.speaker.identification  D  addCallback activity:androidx.compose.ui.tooling.PreviewActivity animationController:com.qinggan.multidisplay.ActivityAnimationController@f76d8ce
2020-01-02 03:13:02.547 32067-32067 .identificatio          com...a.onnx.speaker.identification  W  Class androidx.compose.runtime.snapshots.SnapshotStateMap failed lock verification and will run slower.
                                                                                                    Common causes for lock verification issues are non-optimized dex code
                                                                                                    and incorrect proguard optimizations.
2020-01-02 03:13:02.664 32067-32090 AdrenoGLES-0            com...a.onnx.speaker.identification  I  QUALCOMM build                   : 922e14ee2f, I1af6129815
                                                                                                    Build Date                       : 05/23/22
                                                                                                    OpenGL ES Shader Compiler Version: EV031.30.02.00
                                                                                                    Local Branch                     : mybranchecdab49b-90a9-f156-8887-3cecef3a8cd2
                                                                                                    Remote Branch                    : quic/gfx-adreno.lnx.1.0.3.r3-rel
                                                                                                    Remote Branch                    : NONE
                                                                                                    Reconstruct Branch               : NOTHING
2020-01-02 03:13:02.664 32067-32090 AdrenoGLES-0            com...a.onnx.speaker.identification  I  Build Config                     : S P 10.0.6 AArch64
2020-01-02 03:13:02.664 32067-32090 AdrenoGLES-0            com...a.onnx.speaker.identification  I  Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2020-01-02 03:13:02.707 32067-32090 AdrenoGLES-0            com...a.onnx.speaker.identification  I  PFP: 0x00000000, ME: 0x00000000
2020-01-02 03:13:02.713 32067-32090 Adreno-GSL_RPC          com...a.onnx.speaker.identification  I  <gsl_context_create:2928>: ctxt_id 114, sync_type 2
2020-01-02 03:13:02.719 32067-32090 AdrenoUtils             com...a.onnx.speaker.identification  W  <ReadGpuID_from_sysfs:198>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
2020-01-02 03:13:02.719 32067-32090 AdrenoUtils             com...a.onnx.speaker.identification  W  <ReadGpuID:222>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
2020-01-02 03:13:02.720 32067-32090 Adreno-GSL_RPC          com...a.onnx.speaker.identification  I  <gsl_library_close:1573>:  library close -- refcount=1
2020-01-02 03:13:02.729 32067-32090 Adreno-GSL_RPC          com...a.onnx.speaker.identification  I  <gsl_context_create:2928>: ctxt_id 115, sync_type 2
2020-01-02 03:13:03.044 32067-32067 .identificatio          com...a.onnx.speaker.identification  W  Class androidx.compose.runtime.snapshots.SnapshotStateList failed lock verification and will run slower.
--------- beginning of crash
2020-01-02 03:13:03.177 32067-32067 AndroidRuntime          com...a.onnx.speaker.identification  D  Shutting down VM
2020-01-02 03:13:03.183 32067-32067 AndroidRuntime          com...a.onnx.speaker.identification  E  FATAL EXCEPTION: main
                                                                                                    Process: com.k2fsa.sherpa.onnx.speaker.identification, PID: 32067
                                                                                                    java.lang.NullPointerException
                                                                                                    	at com.k2fsa.sherpa.onnx.SpeakerRecognition.getManager(Speaker.kt:165)
                                                                                                    	at com.k2fsa.sherpa.onnx.speaker.identification.screens.HomeKt.HomeButtonRow(Home.kt:188)
                                                                                                    	at com.k2fsa.sherpa.onnx.speaker.identification.screens.HomeKt.HomeScreen(Home.kt:151)
                                                                                                    	at com.k2fsa.sherpa.onnx.speaker.identification.ComposableSingletons$MainActivityKt$lambda-6$1.invoke(MainActivity.kt:130)
                                                                                                    	at com.k2fsa.sherpa.onnx.speaker.identification.ComposableSingletons$MainActivityKt$lambda-6$1.invoke(MainActivity.kt:129)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:138)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(NavHost.kt:308)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(NavHost.kt:306)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:65)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:52)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:51)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider(NavBackStackEntryProvider.kt:47)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$14.invoke(NavHost.kt:306)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$14.invoke(NavHost.kt:295)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:138)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$4.invoke(AnimatedContent.kt:780)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$4.invoke(AnimatedContent.kt:769)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:941)
                                                                                                    	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedVisibility(AnimatedVisibility.kt:607)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke(AnimatedContent.kt:757)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke(AnimatedContent.kt:740)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:794)
                                                                                                    	at androidx.navigation.compose.NavHostKt.NavHost(NavHost.kt:273)
                                                                                                    	at androidx.navigation.compose.NavHostKt.NavHost(NavHost.kt:128)
                                                                                                    	at com.k2fsa.sherpa.onnx.speaker.identification.MainActivityKt.NavigationHost(MainActivity.kt:128)
                                                                                                    	at com.k2fsa.sherpa.onnx.speaker.identification.MainActivityKt$MainScreen$2.invoke(MainActivity.kt:116)
2020-01-02 03:13:03.185 32067-32067 AndroidRuntime          com...a.onnx.speaker.identification  E  	at com.k2fsa.sherpa.onnx.speaker.identification.MainActivityKt$MainScreen$2.invoke(MainActivity.kt:114)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.material3.ScaffoldKt$ScaffoldLayout$1$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:239)
                                                                                                    	at androidx.compose.material3.ScaffoldKt$ScaffoldLayout$1$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:221)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:1067)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:701)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3340)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3273)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:588)
                                                                                                    	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1013)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:4007)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:520)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcomposeInto(SubcomposeLayout.kt:721)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:694)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:685)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:669)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:1014)
                                                                                                    	at androidx.compose.material3.ScaffoldKt$ScaffoldLayout$1$1$1.invoke(Scaffold.kt:221)
                                                                                                    	at androidx.compose.material3.ScaffoldKt$ScaffoldLayout$1$1$1.invoke(Scaffold.kt:128)
                                                                                                    	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:70)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1$measure$1.placeChildren(SubcomposeLayout.kt:879)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.kt:365)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.kt:357)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2299)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:83)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.layoutChildren(LayoutNodeLayoutDelegate.kt:357)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.onNodePlaced$ui_release(LayoutNodeLayoutDelegate.kt:493)
                                                                                                    	at androidx.compose.ui.node.InnerNodeCoordinator.placeAt-f8xVGno(InnerNodeCoordinator.kt:160)
                                                                                                    	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:34)
                                                                                                    	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:450)
2020-01-02 03:13:03.187 32067-32067 AndroidRuntime          com...a.onnx.speaker.identification  E  	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:683)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:678)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2299)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutModifierSnapshotReads$ui_release(OwnerSnapshotObserver.kt:98)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeOuterCoordinator-f8xVGno(LayoutNodeLayoutDelegate.kt:678)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeAt-f8xVGno(LayoutNodeLayoutDelegate.kt:656)
                                                                                                    	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:34)
                                                                                                    	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:450)
                                                                                                    	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:225)
                                                                                                    	at androidx.compose.foundation.layout.BoxKt.placeInBox(Box.kt:185)
                                                                                                    	at androidx.compose.foundation.layout.BoxKt.access$placeInBox(Box.kt:1)
                                                                                                    	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1$measure$2.invoke(Box.kt:125)
                                                                                                    	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1$measure$2.invoke(Box.kt:124)
                                                                                                    	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:70)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.kt:365)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.kt:357)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2299)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:83)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.layoutChildren(LayoutNodeLayoutDelegate.kt:357)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.onNodePlaced$ui_release(LayoutNodeLayoutDelegate.kt:493)
                                                                                                    	at androidx.compose.ui.node.InnerNodeCoordinator.placeAt-f8xVGno(InnerNodeCoordinator.kt:160)
                                                                                                    	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:34)
                                                                                                    	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer(Placeable.kt:473)
                                                                                                    	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Placeable.kt:288)
                                                                                                    	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:648)
                                                                                                    	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:647)
                                                                                                    	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:70)
                                                                                                    	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(LayoutModifierNodeCoordinator.kt:172)
                                                                                                    	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:34)
                                                                                                    	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer-aW-9-wM(Placeable.kt:476)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:685)
2020-01-02 03:13:03.189 32067-32067 AndroidRuntime          com...a.onnx.speaker.identification  E  	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:678)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2299)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutModifierSnapshotReads$ui_release(OwnerSnapshotObserver.kt:98)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeOuterCoordinator-f8xVGno(LayoutNodeLayoutDelegate.kt:678)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeAt-f8xVGno(LayoutNodeLayoutDelegate.kt:656)
                                                                                                    	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:34)
                                                                                                    	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelativeWithLayer(Placeable.kt:465)
                                                                                                    	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelativeWithLayer$default(Placeable.kt:268)
                                                                                                    	at androidx.compose.ui.layout.RootMeasurePolicy$measure$2.invoke(RootMeasurePolicy.kt:43)
                                                                                                    	at androidx.compose.ui.layout.RootMeasurePolicy$measure$2.invoke(RootMeasurePolicy.kt:39)
                                                                                                    	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:70)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.kt:365)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.kt:357)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2299)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:83)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.layoutChildren(LayoutNodeLayoutDelegate.kt:357)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.onNodePlaced$ui_release(LayoutNodeLayoutDelegate.kt:493)
                                                                                                    	at androidx.compose.ui.node.InnerNodeCoordinator.placeAt-f8xVGno(InnerNodeCoordinator.kt:160)
                                                                                                    	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:34)
                                                                                                    	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:450)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:683)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:678)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2299)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutModifierSnapshotReads$ui_release(OwnerSnapshotObserver.kt:98)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeOuterCoordinator-f8xVGno(LayoutNodeLayoutDelegate.kt:678)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeAt-f8xVGno(LayoutNodeLayoutDelegate.kt:656)
                                                                                                    	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:34)
2020-01-02 03:13:03.191 32067-32067 AndroidRuntime          com...a.onnx.speaker.identification  E  	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative(Placeable.kt:439)
                                                                                                    	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative$default(Placeable.kt:201)
                                                                                                    	at androidx.compose.ui.node.LayoutNode.place$ui_release(LayoutNode.kt:896)
                                                                                                    	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:467)
                                                                                                    	at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:39)
                                                                                                    	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:344)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.onLayout(AndroidComposeView.android.kt:997)
                                                                                                    	at android.view.View.layout(View.java:22854)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6415)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView.internalOnLayout$ui_release(ComposeView.android.kt:322)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView.onLayout(ComposeView.android.kt:313)
                                                                                                    	at android.view.View.layout(View.java:22854)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6415)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:22854)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6415)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
                                                                                                    	at android.view.View.layout(View.java:22854)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6415)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at com.android.internal.policy.DecorView.onLayout(DecorView.java:814)
                                                                                                    	at android.view.View.layout(View.java:22854)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6415)
                                                                                                    	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3557)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3025)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2023)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8285)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:731)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7663)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2020-01-02 03:13:03.207 32067-32067 Process                 com...a.onnx.speaker.identification  I  Sending signal. PID: 32067 SIG: 9

```

**Comment by csukuangfj** [comment]
Are you able to run with pre-built APKs?

https://k2-fsa.github.io/sherpa/onnx/speaker-identification/apk.html

**Comment by tianmala** [comment]
yes , apk can run , but code can't ,i don't know why

**Comment by csukuangfj** [comment]
The log you provided is too limited.

Please start the capture before the app is started.

It would be best to capture the config params to create the TTS instance.

**Comment by tianmala** [comment]
thx a lot ,i have solved this problem

**Comment by csukuangfj** [comment]
Could you tell us how you fixed it?
